name: Deploy-React.js

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code. 
        uses: actions/checkout@v2
      - name: Check Node v 
        run: node -v
      - name: Install Dependencies 
        run: yarn install --frozen-lockfile
      - name: Build 
        run: yarn build
      - name: zip create
        run: zip -qq -r ./vs_dp_web_build.zip . 
        shell: bash
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ secrets.AWS_REGION }} 
      - name: Upload to S3 
        run: | 
          aws s3 cp --region ap-northeast-2 ./vs_dp_web_build.zip s3://vs-dp-github-action-s3-bucket/build/vs_dp_web_build.zip
      - name: Deploy 
        run: aws deploy create-deployment
          --application-name vs-dp-codedeploy-app 
          --deployment-config-name CodeDeployDefault.AllAtOnce 
          --deployment-group-name vs-dp-codedeploy-deployment-group 
          --s3-location bucket=vs-dp-github-action-s3-bucket,bundleType=zip 
